language: python
python:
  - "2.7"
  - "3.5"
cache: pip
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade pytest-cov
  - pip install --upgrade wheel
  - pip install --upgrade setuptools
  - pip install --upgrade codecov pytest pytest-cov
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - py.test --cov stormstats --cov-report xml --cov-report term
  - travis-sphinx build
after_success:
  - codecov
  - travis-sphinx deploy
